In [ ]:
import pandas as pd
import matplotlib.pyplot as pyplot
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler

In [92]:
df = pd.read_csv('/users/imbahndu/Desktop/Columbia DBM/Typing dataset/typing.csv', low_memory=False)

In [93]:
df.head()

,Unnamed: 0,UserKey,Date,Timestamp,Hand,HoldTime,Direction,LatencyTime,FlightTime,Filename,...,Parkinsons,Tremors,DiagnosisYear,Sided,UPDRS,Impact,Levadopa,DA,MAOB,Other
0,0,0EA27ICBLF,160722,18:41:04.336,L,0101.6,LL,0234.4,0156.3,0EA27ICBLF_1607.txt,...,True,True,2000,Left,Don't know,Severe,True,True,False,False
1,1,0EA27ICBLF,160722,18:42:14.070,L,0085.9,LL,0437.5,0359.4,0EA27ICBLF_1607.txt,...,True,True,2000,Left,Don't know,Severe,True,True,False,False
2,2,0EA27ICBLF,160722,18:42:14.273,L,0078.1,LL,0210.9,0125.0,0EA27ICBLF_1607.txt,...,True,True,2000,Left,Don't know,Severe,True,True,False,False
3,3,0EA27ICBLF,160722,18:42:14.617,L,0062.5,LL,0359.4,0281.3,0EA27ICBLF_1607.txt,...,True,True,2000,Left,Don't know,Severe,True,True,False,False
4,4,0EA27ICBLF,160722,18:42:15.586,S,0125.0,LS,0187.5,0093.8,0EA27ICBLF_1607.txt,...,True,True,2000,Left,Don't know,Severe,True,True,False,False

In [94]:
#Finding out the number of missing values
null_series = df.isnull().sum()

print(null_series)

print(type(null_series))

Unnamed: 0             0
UserKey                0
Date                   0
Timestamp              0
Hand                   0
HoldTime               0
Direction              0
LatencyTime            0
FlightTime             2
Filename               0
BirthYear        2153339
Gender            301987
Parkinsons        301987
Tremors           301987
DiagnosisYear    1469539
Sided            3498254
UPDRS             301987
Impact            480998
Levadopa          301987
DA                301987
MAOB              301987
Other             301987
dtype: int64
<class 'pandas.core.series.Series'>

In [95]:
#Dropping all the rows with couts 301987
rows_to_drop = []
for col in range(len(null_series)):
    if null_series[col] == 301987:
        rows_to_drop.append(col)

columns = [] 
for row in rows_to_drop:
    columns.append(df.columns[row])

print(columns)

df = df.dropna(subset = columns)
print(df)

['Gender', 'Parkinsons', 'Tremors', 'UPDRS', 'Levadopa', 'DA', 'MAOB', 'Other']

/tmp/ipykernel_956201/2088116909.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if null_series[col] == 301987:

         Unnamed: 0     UserKey    Date     Timestamp Hand HoldTime Direction  \
0                 0  0EA27ICBLF  160722  18:41:04.336    L   0101.6        LL
1                 1  0EA27ICBLF  160722  18:42:14.070    L   0085.9        LL
2                 2  0EA27ICBLF  160722  18:42:14.273    L   0078.1        LL
3                 3  0EA27ICBLF  160722  18:42:14.617    L   0062.5        LL
4                 4  0EA27ICBLF  160722  18:42:15.586    S   0125.0        LS
...             ...         ...     ...           ...  ...      ...       ...
9316853     9316853  ZYWLN4JVLA  170126  13:56:20.117    L   0195.3        RL
9316854     9316854  ZYWLN4JVLA  170126  13:56:20.242    R   0105.5        LR
9316855     9316855  ZYWLN4JVLA  170126  13:56:33.625    L   0168.0        LL
9316856     9316856  ZYWLN4JVLA  170126  13:56:33.836    L   0097.7        LL
9316857     9316857  ZYWLN4JVLA  170126  13:56:34.066    L   0168.0        LL

        LatencyTime FlightTime             Filename  ...  Parkinsons Tremors  \
0            0234.4     0156.3  0EA27ICBLF_1607.txt  ...        True    True
1            0437.5     0359.4  0EA27ICBLF_1607.txt  ...        True    True
2            0210.9     0125.0  0EA27ICBLF_1607.txt  ...        True    True
3            0359.4     0281.3  0EA27ICBLF_1607.txt  ...        True    True
4            0187.5     0093.8  0EA27ICBLF_1607.txt  ...        True    True
...             ...        ...                  ...  ...         ...     ...
9316853      0425.8      261.7  ZYWLN4JVLA_1701.txt  ...        True   False
9316854      0214.8       19.5  ZYWLN4JVLA_1701.txt  ...        True   False
9316855      0332.0       15.6  ZYWLN4JVLA_1701.txt  ...        True   False
9316856      0281.3      113.3  ZYWLN4JVLA_1701.txt  ...        True   False
9316857      0160.2       62.5  ZYWLN4JVLA_1701.txt  ...        True   False

        DiagnosisYear  Sided       UPDRS  Impact Levadopa    DA   MAOB  Other
0                2000   Left  Don't know  Severe     True  True  False  False
1                2000   Left  Don't know  Severe     True  True  False  False
2                2000   Left  Don't know  Severe     True  True  False  False
3                2000   Left  Don't know  Severe     True  True  False  False
4                2000   Left  Don't know  Severe     True  True  False  False
...               ...    ...         ...     ...      ...   ...    ...    ...
9316853           NaN  Right  Don't know  Medium     True  True   True   True
9316854           NaN  Right  Don't know  Medium     True  True   True   True
9316855           NaN  Right  Don't know  Medium     True  True   True   True
9316856           NaN  Right  Don't know  Medium     True  True   True   True
9316857           NaN  Right  Don't know  Medium     True  True   True   True

[9014871 rows x 22 columns]

In [96]:
#Verifying if code worked and all rows with 301987
df.isnull().sum()

Unnamed: 0             0
UserKey                0
Date                   0
Timestamp              0
Hand                   0
HoldTime               0
Direction              0
LatencyTime            0
FlightTime             2
Filename               0
BirthYear        1851352
Gender                 0
Parkinsons             0
Tremors                0
DiagnosisYear    1167552
Sided            3196267
UPDRS                  0
Impact            179011
Levadopa               0
DA                     0
MAOB                   0
Other                  0
dtype: int64

In [97]:
#Dropping the unnamed column --> don't see why it's necessary
df.drop(columns = "Unnamed: 0")

,UserKey,Date,Timestamp,Hand,HoldTime,Direction,LatencyTime,FlightTime,Filename,BirthYear,...,Parkinsons,Tremors,DiagnosisYear,Sided,UPDRS,Impact,Levadopa,DA,MAOB,Other
0,0EA27ICBLF,160722,18:41:04.336,L,0101.6,LL,0234.4,0156.3,0EA27ICBLF_1607.txt,1952.0,...,True,True,2000,Left,Don't know,Severe,True,True,False,False
1,0EA27ICBLF,160722,18:42:14.070,L,0085.9,LL,0437.5,0359.4,0EA27ICBLF_1607.txt,1952.0,...,True,True,2000,Left,Don't know,Severe,True,True,False,False
2,0EA27ICBLF,160722,18:42:14.273,L,0078.1,LL,0210.9,0125.0,0EA27ICBLF_1607.txt,1952.0,...,True,True,2000,Left,Don't know,Severe,True,True,False,False
3,0EA27ICBLF,160722,18:42:14.617,L,0062.5,LL,0359.4,0281.3,0EA27ICBLF_1607.txt,1952.0,...,True,True,2000,Left,Don't know,Severe,True,True,False,False
4,0EA27ICBLF,160722,18:42:15.586,S,0125.0,LS,0187.5,0093.8,0EA27ICBLF_1607.txt,1952.0,...,True,True,2000,Left,Don't know,Severe,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9316853,ZYWLN4JVLA,170126,13:56:20.117,L,0195.3,RL,0425.8,261.7,ZYWLN4JVLA_1701.txt,NaN,...,True,False,NaN,Right,Don't know,Medium,True,True,True,True
9316854,ZYWLN4JVLA,170126,13:56:20.242,R,0105.5,LR,0214.8,19.5,ZYWLN4JVLA_1701.txt,NaN,...,True,False,NaN,Right,Don't know,Medium,True,True,True,True
9316855,ZYWLN4JVLA,170126,13:56:33.625,L,0168.0,LL,0332.0,15.6,ZYWLN4JVLA_1701.txt,NaN,...,True,False,NaN,Right,Don't know,Medium,True,True,True,True
9316856,ZYWLN4JVLA,170126,13:56:33.836,L,0097.7,LL,0281.3,113.3,ZYWLN4JVLA_1701.txt,NaN,...,True,False,NaN,Right,Don't know,Medium,True,True,True,True
9316857,ZYWLN4JVLA,170126,13:56:34.066,L,0168.0,LL,0160.2,62.5,ZYWLN4JVLA_1701.txt,NaN,...,True,False,NaN,Right,Don't know,Medium,True,True,True,True

In [98]:
df["Parkinsons"].value_counts()

#Will balance this during preprocessing

Parkinsons
True     6470722
False    2544149
Name: count, dtype: int64

In [99]:
#Checking the URPDS column
df["UPDRS"].value_counts()

UPDRS
Don't know    8203052
4              717717
3               68171
2               25922
1                   9
Name: count, dtype: int64

In [100]:
#Dropping columns (both categorical and numerical col) that will not impact a model
df = df.drop(columns = ["BirthYear", "UserKey", "Tremors", "DiagnosisYear", "Sided", "Impact", "UPDRS", "Levadopa", "MAOB", "DA", "Other", "Unnamed: 0", "Date", "Filename", "Timestamp"])

In [101]:
#One hot enconding teh gender
df = pd.get_dummies(df, columns=["Gender"],drop_first=True)

In [102]:
df.head(10)

  Hand HoldTime Direction LatencyTime FlightTime Parkinsons  Gender_Male
0    L   0101.6        LL      0234.4     0156.3       True        False
1    L   0085.9        LL      0437.5     0359.4       True        False
2    L   0078.1        LL      0210.9     0125.0       True        False
3    L   0062.5        LL      0359.4     0281.3       True        False
4    S   0125.0        LS      0187.5     0093.8       True        False
5    L   0078.1        SL      0226.6     0101.6       True        False
6    R   0085.9        LR      0195.3     0117.2       True        False
7    R   0085.9        RR      0359.4     0296.9       True        False
8    L   0070.3        RL      0429.7     0343.8       True        False
9    L   0101.6        LL      0406.3     0335.9       True        False

In [103]:
#Printing the types of all columns
print(df.dtypes)

Hand           object
HoldTime       object
Direction      object
LatencyTime    object
FlightTime     object
Parkinsons     object
Gender_Male      bool
dtype: object

In [104]:
#Drooping the expected numerical columns to float
expected_numerical = ["HoldTime", "LatencyTime", "FlightTime"]

# Convert columns to numeric, else convert them to NAN
for col in expected_numerical:

    df[col] = pd.to_numeric(df[col], errors='coerce')

# Drop rows with NaN in any of the expected numeric columns
df.dropna(subset=expected_numerical, inplace=True)

In [105]:
#Converting the string literal of PD to bool 

df["Parkinsons"] = df["Parkinsons"].astype(bool)

In [106]:
print(df.dtypes)

Hand            object
HoldTime       float64
Direction       object
LatencyTime    float64
FlightTime     float64
Parkinsons        bool
Gender_Male       bool
dtype: object

In [ ]:
#One hot encoding catgorical variables

cat_columns =[col for col in df.columns if df[col].dtype == "object"]

#Saving numerical columns just in case
num_columns = [col for col in df.columns if df[col].dtype == "float64" or df[col].dtype == "int64"]

df = pd.get_dummies(df, columns=cat_columns, dtype=float)

In [108]:
df

,HoldTime,LatencyTime,FlightTime,Parkinsons,Gender_Male,Hand_L,Hand_R,Hand_S,Direction_LL,Direction_LR,Direction_LS,Direction_RL,Direction_RR,Direction_RS,Direction_SL,Direction_SR,Direction_SS
0,101.6,234.4,156.3,True,False,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,85.9,437.5,359.4,True,False,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,78.1,210.9,125.0,True,False,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,62.5,359.4,281.3,True,False,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,125.0,187.5,93.8,True,False,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9316853,195.3,425.8,261.7,True,False,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9316854,105.5,214.8,19.5,True,False,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9316855,168.0,332.0,15.6,True,False,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9316856,97.7,281.3,113.3,True,False,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9316857,168.0,160.2,62.5,True,False,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [109]:
num_columns

['HoldTime', 'LatencyTime', 'FlightTime']

In [ ]:
#Scaling the numerical columns
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(df[num_columns])

scaler.fit_transform(df[num_columns])

print(scaler.mean_)

[[ 3.69732757e-04 -1.84913091e-01 -2.34146322e-01]
 [ 1.26641231e-04  1.28446960e+00  1.35272232e+00]
 [ 5.86964522e-06 -3.54930291e-01 -4.78700673e-01]
 ...
 [ 1.39783959e-03  5.21200896e-01 -1.33346892e+00]
 [ 3.09346964e-04  1.54397831e-01 -5.70115558e-01]
 [ 1.39783959e-03 -7.21733356e-01 -9.67028051e-01]]
[ 77.72091056 259.95892963 186.26789817]

In [120]:
#Keeping the preprocessed file another csv to facilate modeling

df.to_csv("modeling.csv", index=False)